# Generated by Django 5.1.1 on 2024-10-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('employment_date', models.DateField(verbose_name='Дата приема на работу')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers_photos/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Неизвестный маршрут', max_length=30, verbose_name='Название')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
                ('travel_days', models.IntegerField(verbose_name='Дней в пути')),
                ('payment', models.IntegerField(verbose_name='Оплата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('return_date', models.DateField(verbose_name='Дата возвращения')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Премия')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание перевозки')),
                ('document_number', models.CharField(max_length=30, verbose_name='Номер документа')),
                ('insurance', models.BooleanField(default=False, verbose_name='Наличие страховки')),
                ('transportation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cargo.transportations', verbose_name='Перевозка')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True, verbose_name='Номер транспортного средства')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('capacity', models.IntegerField(verbose_name='Грузоподъемность (кг)')),
                ('transportations', models.ManyToManyField(to='cargo.transportations')),
            ],
        ),
        migrations.CreateModel(
            name='DriversTransportations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_hours', models.IntegerField(verbose_name='Часы в пути')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.drivers')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.transportations')),
            ],
        ),
    ]
