# Generated by Django 5.1.1 on 2024-10-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivers',
            options={'ordering': ['surname'], 'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='driverstransportations',
            options={'verbose_name': 'Связь Водителя и Перевозки', 'verbose_name_plural': 'Связи Водителей и Перевозок'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'ordering': ['name'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['model'], 'verbose_name': 'Транспорт', 'verbose_name_plural': 'Транспорт'},
        ),
        migrations.AlterModelOptions(
            name='transportationdetails',
            options={'verbose_name': 'Детали перевозки', 'verbose_name_plural': 'Детали перевозок'},
        ),
        migrations.AlterModelOptions(
            name='transportations',
            options={'ordering': ['departure_date'], 'verbose_name': 'Перевозка', 'verbose_name_plural': 'Перевозки'},
        ),
        migrations.RemoveField(
            model_name='transport',
            name='transportations',
        ),
        migrations.AddField(
            model_name='driverstransportations',
            name='transport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cargo.transport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportations',
            name='route',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cargo.routes', verbose_name='Маршрут'),
            preserve_default=False,
        ),
    ]
